### PR TITLE
fix the deprication warning for inline_policy on aws_iam_role resource

### PR DESCRIPTION
**Pull request by glg-satish-tripathi**
## Description of the change

> This gives a deprecation notice if we run it with aws provider > 5 version. This PR fixes that issue. 
image

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue);
- [X] New feature (non-breaking change that adds functionality);
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected);
- [ ] Documentation (a documentation or example fix not affecting the infrastructure managed by this module);

### Development

- [x] All necessary variables have been defined, with defaults if applicable;
- [X] The code is formatted properly;

### Code review

- [x] The module version is bumped accordingly;
- [x] Spacelift tests are passing;
- [x] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached;
- [x] This pull request is no longer marked as "draft";
- [x] Reviewers have been assigned;
- [x] Changes have been reviewed by at least one other engineer;

### CODE REVIEW

**Review by adamconnelly — APPROVED** [review]
LGTM - thanks for the contribution. I'll just ask for one more reviewer from the Spacelift team.

**Review by TheMacies — APPROVED** [review]

**Comment by lorengordon** [comment]
@adamconnelly @TheMacies As I mentioned on https://github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2/pull/102#discussion_r1810903057, this change is actually backwards incompatible... Might be nice to add a note somewhere for folks upgrading from an earlier version, helping them figure out how to upgrade without error.

See the upstream discussion for more details: https://github.com/hashicorp/terraform-provider-aws/issues/39376#issuecomment-2363922272

**Comment by adamconnelly** [comment]
@lorengordon I just want to double check this with you to understand the backwards compatibility issue better. I tested this out locally by doing the following:

1. Applying v2.6.2 of the module.
2. Applying v2.6.3 of the module.

As expected, I end up with a new `aws_iam_role_policy` resource being created, however it applies cleanly. The plan didn't include a removal of the `inline_policy` attribute, which surprised me but I guess is a good thing.

Could you explain what you expect to happen here to help me understand it?

**Comment by lorengordon** [comment]
Oh, inline policies. I forget they are weird like that. When the inline policy name is the same, the AWS PutRolePolicy API actually just _overwrites_ the existing policy with the "new" contents. Which is probably actually fine in this case! Pardon the noise then!

The APIs for _other_ resources do not work that way, and would fail if the association were already present. I like this new exclusive attachment feature, but it's definitely taking me deeper into API behaviors than normally have to go!

**Comment by adamconnelly** [comment]
Cool - no problem at all - thanks a lot for raising this. It's way better that we double checked it than caused problems.

🙇

**Comment by glg-satish-tripathi** [comment]
@adamconnelly @lorengordon  i did looked at https://github.com/hashicorp/terraform-provider-aws/issues/39376 discussion prior to creating this pull request but i totally missed to mention this in the pull request comment.

**Comment by adamconnelly** [comment]
No worries @glg-satish-tripathi!

**Pull request merged**
