### PR TITLE
Add support for instance refresh

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
## Description of the change

Recycle instances if the instance configuration changes.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue);
- [x] New feature (non-breaking change that adds functionality);
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected);
- [ ] Documentation (a documentation or example fix not affecting the infrastructure managed by this module);

### Development

- [x] All necessary variables have been defined, with defaults if applicable;
- [x] The code is formatted properly;

### Code review

- [ ] The module version is bumped accordingly;
- [ ] Spacelift tests are passing;
- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached;
- [x] This pull request is no longer marked as "draft";
- [ ] Reviewers have been assigned;
- [ ] Changes have been reviewed by at least one other engineer;

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
ping

**Comment by nitrocode** [comment]
@alexjurkiewicz if an `instance_refresh` is used, wouldn't you also require a lifecycle hook to prevent terminating an instance that is currently running terraform ?

**Comment by alexjurkiewicz** [comment]
Yes possibly. We stopped tweaking our worker pools so I don't have a
personal need for instance-refresh-on-update any more. So I won't be
investigating or updating this PR.

**Comment by adamconnelly** [comment]
I'm closing this since it's not being worked on anymore, and it sounds like there would be more involved (i.e. the lifecycle hooks to prevent terminating an instance that was processing an in-progress run).

**Pull request closed without merging**
