### PR TITLE
fix: Lambda download during worker pool recreation, remove temp file

### PR DESCRIPTION
**Pull request by MaxymVlasov**
## Description of the change

* Fix `mkdir` error: "cannot create directory ‘lambda’: File exists"
* Fix `unzip` interactive prompt/error: replace LICENSE? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
* Remove temporary zip file

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue);
- [ ] New feature (non-breaking change that adds functionality);
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected);
- [ ] Documentation (a documentation or example fix not affecting the infrastructure managed by this module);

### Development

- [ ] All necessary variables have been defined, with defaults if applicable;
- [ ] The code is formatted properly;

### Code review

- [ ] The module version is bumped accordingly;
- [ ] Spacelift tests are passing;
- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached;
- [ ] This pull request is no longer marked as "draft";
- [ ] Reviewers have been assigned;
- [ ] Changes have been reviewed by at least one other engineer;

### CODE REVIEW

**Comment by adamconnelly** [comment]
@eminalemdar could you take a look at this one? I think you added the autoscaler code, so are probably best placed to review this.

**Review by peterdeme — APPROVED** [review]

**Review by eminalemdar — APPROVED** [review]
LGTM! Thank you for your contribution

**Comment by eminalemdar** [comment]
@MaxymVlasov can you please rebase on `main` for this PR because this branch is out-of-date. and also the in order to docs check to run you should push another commit for that.

**Comment by MaxymVlasov** [comment]
Done

**Pull request merged**
